apiVersion: v1
kind: ConfigMap
metadata:
  name: unifiap-config
  namespace: unifiapay
data:
  RESERVA_BANCARIA_SALDO: "1000.00"

---
apiVersion: v1
kind: Secret
metadata:
  name: unifiap-secrets
  namespace: unifiapay
type: Opaque
stringData:
  pix.key: "SIMULATED-PIX-KEY-PLACEHOLDER"
