apiVersion: v1
kind: Pod
metadata:
  name: insecure-deploy-test
  namespace: unifiapay
spec:
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  containers:
  - name: test
    image: busybox
    command: ["sleep","3600"]
    securityContext:
      privileged: true
